const PDFDocument = require("pdfkit");

function generatePDF(data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks = [];

      doc.on("data", chunk => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      doc.fontSize(20).text("Chess Analyzer Report", {
        align: "center",
      });

      doc.moveDown();

      doc.fontSize(14).text(`Player Name: ${data.name || "N/A"}`);
      doc.text(`Rating: ${data.rating || "N/A"}`);
      doc.text(`Games Analyzed: ${data.games || "N/A"}`);

      doc.moveDown();

      doc.fontSize(12).text("Insights:");
      doc.text(data.insights || "No insights available");

      doc.moveDown();

      doc.fontSize(10).text("Generated by Chess Analyzer", {
        align: "center",
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePDF };