const ecoMap = {
  // Flank / Irregular
  "A00": "Uncommon Opening",
  "A01": "Nimzowitsch-Larsen Attack",
  "A02": "Bird Opening",
  "A03": "Bird Opening",
  "A04": "Reti Opening",
  "A05": "Reti Opening",
  "A06": "Reti Opening",
  "A07": "King's Indian Attack",
  "A08": "King's Indian Attack",
  "A09": "Reti Opening",

  // English
  "A10": "English Opening",
  "A11": "English Opening",
  "A12": "English Opening",
  "A13": "English Opening",
  "A14": "English Opening",
  "A15": "English Opening",
  "A16": "English Opening",
  "A17": "English Opening",
  "A18": "English Opening",
  "A19": "English Opening",
  "A20": "English Opening",
  "A21": "English Opening",
  "A22": "English Opening",
  "A23": "English Opening",
  "A24": "English Opening",
  "A25": "English Opening",

  // Queen Pawn / Dutch / Benoni
  "A40": "Queen's Pawn Opening",
  "A41": "Queen's Pawn Opening",
  "A42": "Modern Defense",
  "A43": "Old Benoni",
  "A44": "Old Benoni",
  "A45": "Trompowsky Attack",
  "A46": "Queen's Pawn Opening",
  "A47": "Queen's Indian Defense",
  "A48": "King's Indian Defense",
  "A49": "King's Indian Defense",

  // Sicilian / Caro-Kann / Alekhine / Pirc
  "B00": "King's Pawn Opening",
  "B01": "Scandinavian Defense",
  "B02": "Alekhine Defense",
  "B03": "Alekhine Defense",
  "B04": "Alekhine Defense",
  "B05": "Alekhine Defense",
  "B06": "Modern Defense",
  "B07": "Pirc Defense",
  "B08": "Pirc Defense",
  "B09": "Pirc Defense",

  "B10": "Caro-Kann Defense",
  "B11": "Caro-Kann Defense",
  "B12": "Caro-Kann Defense: Advance Variation",
  "B13": "Caro-Kann Defense",
  "B14": "Caro-Kann Defense: Panov Attack",
  "B15": "Caro-Kann Defense",
  "B16": "Caro-Kann Defense",
  "B17": "Caro-Kann Defense",
  "B18": "Caro-Kann Defense: Classical",
  "B19": "Caro-Kann Defense",

  "B20": "Sicilian Defense",
  "B21": "Sicilian Defense: Smith-Morra Gambit",
  "B22": "Sicilian Defense: Alapin Variation",
  "B23": "Sicilian Defense: Closed",
  "B24": "Sicilian Defense: Closed",
  "B25": "Sicilian Defense: Closed",
  "B26": "Sicilian Defense",
  "B27": "Sicilian Defense",
  "B28": "Sicilian Defense",
  "B29": "Sicilian Defense",
  "B30": "Sicilian Defense",
  "B31": "Sicilian Defense: Rossolimo",
  "B32": "Sicilian Defense",
  "B33": "Sicilian Defense",
  "B40": "Sicilian Defense",
  "B50": "Sicilian Defense",
  "B51": "Sicilian Defense: Canal Attack",
  "B52": "Sicilian Defense",
  "B53": "Sicilian Defense",
  "B54": "Sicilian Defense",
  "B55": "Sicilian Defense",
  "B56": "Sicilian Defense",
  "B57": "Sicilian Defense",
  "B58": "Sicilian Defense",
  "B59": "Sicilian Defense",
  "B90": "Sicilian Defense: Najdorf",
  "B91": "Sicilian Defense: Najdorf",
  "B92": "Sicilian Defense: Najdorf",
  "B93": "Sicilian Defense: Najdorf",
  "B94": "Sicilian Defense: Najdorf",
  "B95": "Sicilian Defense: Najdorf",
  "B96": "Sicilian Defense: Najdorf",
  "B97": "Sicilian Defense: Najdorf",
  "B98": "Sicilian Defense: Najdorf",
  "B99": "Sicilian Defense: Najdorf",

  // French
  "C00": "French Defense",
  "C01": "French Defense",
  "C02": "French Defense: Advance Variation",
  "C03": "French Defense: Tarrasch",
  "C04": "French Defense: Tarrasch",
  "C05": "French Defense",
  "C06": "French Defense",
  "C07": "French Defense",
  "C08": "French Defense",
  "C09": "French Defense",

  // Open Games
  "C20": "King's Pawn Game",
  "C21": "Center Game",
  "C22": "Center Game",
  "C23": "Bishop Opening",
  "C24": "Bishop Opening",
  "C25": "Vienna Game",
  "C26": "Vienna Game",
  "C27": "Vienna Game",
  "C28": "Vienna Game",
  "C29": "Vienna Game",

  "C40": "King's Knight Opening",
  "C41": "Philidor Defense",
  "C42": "Petrov Defense",
  "C43": "Petrov Defense",
  "C44": "King's Pawn Game",
  "C45": "Scotch Game",
  "C46": "Three Knights Game",
  "C47": "Four Knights Game",
  "C48": "Four Knights Game",
  "C49": "Four Knights Game",

  // Italian / Ruy Lopez
  "C50": "Italian Game",
  "C51": "Evans Gambit",
  "C52": "Italian Game",
  "C53": "Giuoco Piano",
  "C54": "Italian Game",
  "C55": "Two Knights Defense",
  "C56": "Two Knights Defense",
  "C57": "Italian Game",
  "C58": "Italian Game",
  "C59": "Italian Game",

  "C60": "Ruy Lopez",
  "C61": "Ruy Lopez: Bird Variation",
  "C62": "Ruy Lopez: Old Steinitz",
  "C63": "Ruy Lopez: Schliemann Defense",
  "C64": "Ruy Lopez: Classical",
  "C65": "Ruy Lopez: Berlin Defense",
  "C66": "Ruy Lopez",
  "C67": "Ruy Lopez",
  "C68": "Ruy Lopez",
  "C69": "Ruy Lopez",

  // Queen's Gambit / Slav
  "D00": "Queen's Pawn Game",
  "D02": "Queen's Pawn Game",
  "D06": "Queen's Gambit",
  "D08": "Queen's Gambit",
  "D10": "Queen's Gambit Declined",
  "D20": "Queen's Gambit Accepted",
  "D30": "Queen's Gambit Declined",
  "D31": "Queen's Gambit Declined",
  "D35": "Queen's Gambit Declined",
  "D43": "Semi-Slav Defense",
  "D45": "Semi-Slav Defense",

  // Indian defenses
  "E00": "Catalan Opening",
  "E10": "Queen's Indian Defense",
  "E11": "Bogo-Indian Defense",
  "E12": "Queen's Indian Defense",
  "E20": "Nimzo-Indian Defense",
  "E21": "Nimzo-Indian Defense",
  "E30": "Nimzo-Indian Defense",
  "E32": "Nimzo-Indian Defense",

  "E60": "King's Indian Defense",
  "E61": "King's Indian Defense",
  "E62": "King's Indian Defense",
  "E70": "King's Indian Defense: Classical",
  "E80": "King's Indian Defense: Saemisch",
  "E90": "King's Indian Defense: Main Line"
};

module.exports = ecoMap;